version: '3.1'
services:
  db:
    container_name: mysql_local_consultas
    image: mysql:8.0.43-oracle
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "consultas_medicas"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "1000:3306"
